cmake .. \
  -DCMAKE_C_COMPILER="/usr/pppl/intel/2015-pkgs/openmpi-1.8.4/bin/mpicc" \
  -DCMAKE_CXX_COMPILER="/usr/pppl/intel/2015-pkgs/openmpi-1.8.4/bin/mpicxx" \
  -DCMAKE_Fortran_COMPILER="/usr/pppl/intel/2015-pkgs/openmpi-1.8.4/bin/mpif90" \
  -DCMAKE_C_FLAGS=" -g -O2 -DDEBUG" \
  -DCMAKE_CXX_FLAGS=" -g -O2 -DDEBUG" \
  -DCMAKE_Fortran_FLAGS="-fpic "\
  -DSCOREC_INCLUDE_DIR="/p/tsc/m3dc1/lib/SCORECLib/sunfire/Apr2015-jin/include" \
  -DSCOREC_LIB_DIR="/p/tsc/m3dc1/lib/SCORECLib/sunfire/Apr2015-jin/lib" \
  -DZOLTAN_INCLUDE_DIR="/p/tsc/m3dc1/lib/SCORECLib/sunfire/Apr2015-jin/include" \
  -DZOLTAN_LIBRARY="/p/tsc/m3dc1/lib/SCORECLib/sunfire/Apr2015-jin/lib/libzoltan.a" \
  -DPARMETIS_INCLUDE_DIR="/p/swim/jchen/PETSC/petsc-3.5.3/portalr6-intel-openmpi-1.8.4/include" \
  -DPARMETIS_LIBRARY="/p/swim/jchen/PETSC/petsc-3.5.3/portalr6-intel-openmpi-1.8.4/lib/libparmetis.a" \
  -DMETIS_LIBRARY="/p/swim/jchen/PETSC/petsc-3.5.3/portalr6-intel-openmpi-1.8.4/lib/libmetis.a" \
  -DLAPACK_LIB_DIR="/p/tsc/m3dc1/lib/SCORECLib/sunfire/utilities/create_mesh/lib" \
  -DCMAKE_INSTALL_PREFIX="/p/tsc/m3dc1/lib/SCORECLib/sunfire/utilities/create_mesh" \
  -DENABLE_COMPLEX=OFF \
  -DENABLE_MESHGEN=ON \
  -DSIMMETRIX_INCLUDE_DIR=/usr/pppl/Simmetrix/9.0-150404/include \
  -DSIMMETRIX_LIB_DIR=/usr/pppl/Simmetrix/9.0-150404/lib/x64_rhel5_gcc41 \
  -DENABLE_TESTING=OFF \
  -DCMAKE_BUILD_TYPE=Debug

