cmake .. \
  -DCMAKE_C_COMPILER="/global/babbage/nsg/opt/intel/impi/4.1.3.048/intel64/bin/mpiicc" \
  -DCMAKE_CXX_COMPILER="/global/babbage/nsg/opt/intel/impi/4.1.3.048/intel64/bin/mpiicpc" \
  -DCMAKE_Fortran_COMPILER="/global/babbage/nsg/opt/intel/impi/4.1.3.048/intel64/bin/mpiifort" \
  -DCMAKE_C_FLAGS="-mmic -O3 -g -opt-assume-safe-padding -opt-streaming-stores always -opt-streaming-cache-evict=0 -I$PETSC_DIR/include" \
  -DCMAKE_CXX_FLAGS="-mmic -O3 -g -opt-assume-safe-padding -opt-streaming-stores always -opt-streaming-cache-evict=0 -DMPICH_IGNORE_CXX_SEEK -I$PETSC_DIR/include" \
  -DCMAKE_Fortran_FLAGS="-fpic -mmic -align array64byte -O3 -g -c -r8 -implicitnone -fpp -warn all "\
  -DCMAKE_EXE_LINKER_FLAGS="-mt_mpi  -align array64byte " \
  -DSCOREC_INCLUDE_DIR="/chos/global/project/projectdirs/mp288/babbage/scorec/Jun2015/include" \
  -DSCOREC_LIB_DIR="/chos/global/project/projectdirs/mp288/babbage/scorec/Jun2015/lib" \
  -DZOLTAN_LIBRARY="$ZOLTAN_DIR/lib/libzoltan.a" \
  -DPARMETIS_LIBRARY="$PETSC_DIR/$PETSC_ARCH/lib/libparmetis.a" \
  -DMETIS_LIBRARY="$PETSC_DIR/$PETSC_ARCH/lib/libmetis.a" \
  -DPETSC_INCLUDE_DIR="$PETSC_DIR/$PETSC_ARCH/include" \
  -DPETSC_LIB_DIR="$PETSC_DIR/$PETSC_ARCH/lib" \
  -DHDF5_INCLUDE_DIR="$HDF5_DIR/include" \
  -DHDF5_LIB_DIR="$HDF5_DIR/lib" \
  -DCMAKE_INSTALL_PREFIX="/chos/global/project/projectdirs/mp288/babbage/scorec/Jun2015" \
  -DENABLE_TESTING=OFF \
  -DENABLE_COMPLEX=OFF \
  -DCMAKE_BUILD_TYPE=Debug
